### ISSUE TITLE
Web app

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/field_sensors#12]
- [x] Preliminary design of web app interface (2022.04.26)
- [x] Review preliminary design

**Comment by pmcelhany** [comment]
Update 
[Interface doc](https://docs.google.com/document/d/1fEuwa57X2if4j0FIOUwNqlYIXv_eCr1Zn2rY9eV4Enk/edit)

- [x] Modify inteface doc to new data flow path

**Comment by sjhwa** [comment]
- [ ] ~~Get web server up and running and feed it sample data from Android app ~~(5/4/2022)~~ (5/27/2022)
       (i.e. Develop server side code)~~
- [x] Implement Web Page for downloading CSV file for time-series data (5/6/2022)
       (i.e. Develop client side code)
- [x] Provide Core UI features (Email Alerts, Selection of Data over periods of time in table-format) (5/10/2022)
- [ ] ~~Server Cost analysis ~~(5/10/2022)~~  (5/27/2022)~~
- [x] Implement Additional UI Features (Sensor Selection, Data Visualization) (5/15/2022 <- original due date)

**Comment by pmcelhany** [comment]
looks like a good list

**Comment by pmcelhany** [comment]
alarms not essential until we get continuous live communication

**Comment by pmcelhany** [comment]
2022.05.17

- connect with sebas

**Comment by sjhwa** [comment]
- [x] Set up server for public Traffic ~~(5/17/2022)~~ (5/26/2022)
- [x] Send Sebastian HTTP code info ~~(5/17/2022)~~ (5/26/2022)
- [x] Get local files working again! (5/25/2022)
- [x] Continue with UI Dev ~~(and keep team updated through email!)~~

**Comment by pmcelhany** [comment]
2022.05.24

- [x] get url to sebastian (need to modify security) do this afternoon
- [ ] options for sensor calibration data, alarms, new measurements, lat-lon google map

**Comment by sjhwa** [comment]
An overview for the next few weeks:
**MVP:**
- [x] Feed sample data from Android app for demo 
- [ ] MOST IMPORTANT: handle adding new sensors (in config and in app)
- [ ] Server side: fix missing parameters error
- [ ] Client side: fix user log in screen (i.e. fix deprecated node modules)
- [ ] Fix Stats vs Homepage database data sync bug
- [ ] Only list last 24h below the graph
- [ ] Handling duplicates: new value overwrites old
- [ ] granularity in date selection
- [ ] TESTS: sending lotsssss of data



- [ ] Add measurement alias options
- [x] Sending many JSON Files at once?
- [ ] Add delete data option
- [ ] Remove case sensitivity
- [ ] Calibration tracking?

**Documentation:**
- [ ] analyze server costs, domain name, and possible database needs
- [ ] refactor/ clean up code
- [ ] document everything

**Iterate/ improve:**
- [ ] Make edits to UI/ schema per user input
- [ ] Client side: add more chart options, column names for output file
- [ ] Add oyster icons
- [ ] Add location UI
- [ ] Set up alarms?

**Comment by pmcelhany** [comment]
Capstone 22 issue
