### ISSUE TITLE
Communication Research

### ISSUE THREAD

**Issue by AaronDyer13** [NWFSC-OA-lab/field_sensors#4]
-(Updated 1/26) Communication options presented at Monday meeting. Currently considering GSM and LTE options, and considering service providers based upon cost and coverage. GSM preferred at the moment, although LTE provides longer-term service. Specific modules tend to be suited for specific microcontrollers, so our choice will depend on microcontroller selection.

**Comment by pmcelhany** [comment]
Capstone 22 issue
