### ISSUE TITLE
Bench test durafet with labview

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/field_sensors#8]
- [ ] Wire plug-in power supply,, durafet, labjack, computer
- [ ] Test durafet with windows and labjack software
- [ ]  Read labjack with aurdino

**Comment by pmcelhany** [comment]
Will plan to start step one on 2022.04.26 at 4:00
@michaelmaher114 Can you join the UW team to talk about durafet and labjack, etc. at 4:00 today? perhaps in person at UW oceanograhy?

**Comment by pmcelhany** [comment]
- Research purchase of 24 bit A-to-D aurdino module.
- How read temperature? (constant voltage?)

**Comment by pmcelhany** [comment]
@NWFSC-OA-lab/field-sensors-team Mike can join your durfet wiring meeting at 4:00 today. I sent a calendar invite.

**Comment by AaronDyer13** [comment]
> @NWFSC-OA-lab/field-sensors-team Mike can join your durfet wiring meeting at 4:00 today. I sent a calendar invite.

Sounds good, thanks!

**Comment by pmcelhany** [comment]
- Currently testing with 16bit atd (weird results?)
- need to get 24bit (get it working with 16bit if 24 bit not available). Should be easy to swap atod modules.
- 16bit a to d are pretty available 
- Another capstone with a to d and aurdino

**Comment by pmcelhany** [comment]
2022.05.10 

- reading voltage into aurdino
- next step add pH equation
- add moving average  
- add temperature equation
- resistors for temperature measurement

**Comment by pmcelhany** [comment]
@michaelmaher114 Do we have some tris for durafet calibration we can use for the sensor project?

**Comment by pmcelhany** [comment]
2022.05.17
same tasks as last week

**Comment by pmcelhany** [comment]
- [ ] test temperature and pH (adjust temperature)
- [ ] write data to storage (sd card)
- [ ] put into packet for bluetooth transmission (create a buffer that)

**Comment by pmcelhany** [comment]
Capstone 22 issue
